### ISSUE TITLE
c# code generator

### ISSUE THREAD

**Issue by beyaz** [ProductiveRage/TypeScriptDefinitionParser#1]
Is support export c#  code?

**Comment by ProductiveRage** [comment]
No, sorry, this code is just some that I published when I was looking into parsing TypeScript definitions - I didn't get to writing code to export C#. Partly because I was using Bridge.NET at the time and they have a project called [Retyped](https://medium.com/@geoffreymcgill/massive-update-to-retyped-91248454e72e) that emitted C# bindings from TypeScript definitions. Unfortunately, the Retyped code is closed source but it was enough that it exists because it provided bindings for a large number of popular projects but it also highlighted that the type systems for TS and C# are sufficiently different (even though they look similar in many ways) that it's not possible to automatically generate bindings that feel "native" and so I would recommend that anyone doing something similar consider writing their own bindings by hand because the final result will likely be much more pleasant to consume.
